### ISSUE TITLE
数据的格式和内容有介绍吗

### ISSUE THREAD

**Issue by chaohui2** [8600/douyin-user-data#1]
数据是用数据库存储的吗,使用的是什么类型的数据库
数据储存的具体字段是什么

**Comment by PUGE** [comment]
用的是mysql导出的sql文件
有用户名id 生日 性别 是否是vip用户 人气倍率 学校 城市 绑定微博 注册时间之类的

**Comment by chaohui2** [comment]
> 用的是mysql导出的sql文件
> 有用户名id 生日 性别 是否是vip用户 人气倍率 学校 城市 绑定微博 注册时间之类的
