### ISSUE TITLE
无法保存微云

### ISSUE THREAD

**Issue by Ceila9906** [8600/douyin-user-data#12]
师父 你的档案 无法保存到微云呢
显示" (190049)内容可能违反相关法规"
有办法另外上传吗？
还有..师父你的TG号 搜不到..
我可以提供 云盘给你上传

**Comment by PUGE** [comment]
另外上传时间太久了 算了吧

**Comment by PUGE** [comment]
我重新上传吧 你的号多少 我加你

**Comment by 3llan** [comment]
> 我重新上傳吧你的號多少我加你

TG  @Lycqueen4096

**Comment by Ceila9906** [comment]
> 我重新上传吧 你的号多少 我加你

TG @Lycqueen4096

**Comment by Ceila9906** [comment]
师父,加了的话 说下, 因为国内号注册的TG可能无法直接私聊
我建立了一个 TG临时群,你应该可以直接加入
https://t.me/joinchat/I5WiIxdZudnmfK8bRq2Z5w
