### ISSUE TITLE
保存到MEGA

### ISSUE THREAD

**Issue by 3llan** [8600/douyin-user-data#13]
老哥 数据别分享到微云啊
微云有监控的,容易出事
安全点的话,传到mega吧
然後你那没法保存,网页微云下载太慢了...

**Comment by PUGE** [comment]
我重新上传吧

**Comment by PUGE** [comment]
https://mega.nz/#!HyoQGKzB!i7P2loOQo_fiWn76uSBujQ5gpk6cEOojrUGXonSwGbo
https://mega.nz/#!2rxyzAaa!Fyw1dMtuK95mkWpLxeBPxdCklrEqruSCn-HFBVmYuU8
https://mega.nz/#!z3g0mQzJ!ft5Bm_IgJ-D9-60SIElU76mgujG9ndg4r7wk0tM1zoY
https://mega.nz/#!v6hgCQrR!qxk3tW_Ya3WG5P40E0R_z39-wViaCwPBF_sYHSZMwL8
https://mega.nz/#!CypSUSLQ!xDihN4MT9QFeDBxT5wS_VDKdQyB8TUlKNbUb-gbuwP8

**Comment by PUGE** [comment]
https://mega.nz/#!6m42xAiZ!_bqWtb2OrDoO37HNhDvnr47fVfwOW1khRv_yQf30FO4
