### ISSUE TITLE
这是什么格式的文件？解压不出来

### ISSUE THREAD

**Issue by hnlisf** [8600/douyin-user-data#3]
这是什么格式的文件？解压不出来

**Comment by PUGE** [comment]
sql 解压出错？

**Comment by hnlisf** [comment]
没有，我只下载了一个压缩包，就开始解压了。现在已经解压缩出sql文件了，请问下sql文件的编码格式是utf-8的还是默认lantn？

**Comment by hnlisf** [comment]
导入库时会发生各种编码和长度错误：
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAE\xE5\xB7\x9E' for column 'city' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\xB7\x9E' for column 'city' at row 1
ERROR 1406 (22001): Data too long for column 'nickname' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1366 (HY000): Incorrect string value: '\xAD\xE5\x9B\xBD' for column 'country' at row 1
ERROR 1406 (22001): Data too long for column 'city' at row 1

**Comment by PUGE** [comment]
要手动设置有些字段的数据类型

**Comment by hnlisf** [comment]
请问下city和country分别要设置成那种类型？主要是这两个字段存在问题

**Comment by sodalvjian** [comment]
解压出来是葫芦娃吗

**Comment by PUGE** [comment]
![image](https://user-images.githubusercontent.com/9914623/52954945-6571aa80-33c6-11e9-9cbc-fc39543546e1.png)
![image](https://user-images.githubusercontent.com/9914623/52954955-6c98b880-33c6-11e9-9461-8f997b49bd82.png)
![image](https://user-images.githubusercontent.com/9914623/52954959-715d6c80-33c6-11e9-9cd1-efd7e20bc086.png)

**Comment by Mkv4** [comment]
换个链接呗。挂了。

**Comment by PUGE** [comment]
没有啊 你翻墙试试

**Comment by Mkv4** [comment]
ok，get
